global:
  scrape_interval: 3s

scrape_configs:
  - job_name: 'backend'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['backend:8080']
    relabel_configs:
      - source_labels: ['__address__']
        target_label: 'application'
        replacement: 'backend'

